---
- hosts: spines:leafs
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - configure-interfaces
    - restart-switches
    - mv-ntp-mgmt-vrf
    - quagga

- hosts: servers
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - install-docker-ifupdown2
    - configure-interfaces-servers
    - deploy-roh
    - deploy-containers

