---
- hosts: leafs
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - ifupdown2
    - quagga
- hosts: spines
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - ifupdown2
    - quagga
- hosts: servers
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - ifupdown
    - docker
- hosts: servers
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - quagga-docker
- hosts: servers
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - apache-docker
