---
- name: add mgmt vrf
  nclu: 
    atomic: true
    commands:
      - add vrf mgmt
    description: "add mgmt vrf"
  async: 1
  poll: 0
  ignore_errors: true

- name: Reconnect to switches 
  local_action: wait_for port=22 host="{{ inventory_hostname }}" search_regex=OpenSSH delay=1

- name: Stop NTP Daemon
  service: name={{item}} state=stopped enabled=no
  with_items:
  - "ntp"

- name: Start NTP Daemons in MGMT VRF
  service: name={{item}} state=restarted enabled=yes
  with_items:
  - "ntp@mgmt"

