

### install docker
- name: get the docker debian repo's public key
  apt_key: keyserver=p80.pool.sks-keyservers.net id=58118E89F3A912897C070ADBF76221572C52609D

- name: add docker debian repo to sources
  template: src=docker.list.j2 dest=/etc/apt/sources.list.d/docker.list

- name: run apt-get update to add docker to list of available packages
  apt: update_cache=yes

- name: install docker
  apt: name=docker-engine state=present


### start docker
- name: start the docker daemon if it isn't already running
  service: name=docker state=started


