### stop and/or delete previous quagga containers
- name: Stop Any Existing Apache Containers
  shell: docker stop apache_docker
  ignore_errors: yes

- name: Delete Any Existing Apache Containers
  shell: docker rm apache_docker
  ignore_errors: yes

### configure docker-quagga
- name: Create html volume share on host
  file: path=/root/html state=directory mode=0755

- name: Copy Index.html into Server
  template: src=index.html.j2 dest=/root/html/index.html

- name: Copy Index.PHP into Server
  template: src=index.php.j2 dest=/root/html/index.php

### start the container
- name: Create The Apache Container
  shell: docker run -d -p 80:80 -v /root/html:/var/www/html --name apache_docker php:5.6-apache
  ignore_errors: yes

- name: start docker containers (in case not running)
  shell: docker start apache_docker
  ignore_errors: yes
